# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=25)),
                ('trans_type', models.CharField(max_length=15)),
                ('recipient', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
