# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('occupation', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vahay',
            name='email',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
