# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0004_auto_20170715_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vahay',
            name='rent_range',
        ),
        migrations.AddField(
            model_name='vahay',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
