# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0006_auto_20170716_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='vahay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vahay.Vahay'),
        ),
    ]
