# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0007_auto_20170716_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='vahay',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='vahay.Vahay'),
            preserve_default=False,
        ),
    ]
