# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0009_resident_user'),
        ('vahay', '0009_payment'),
    ]

    operations = [
    ]
