# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0010_merge_20170716_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahay.Vahay')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahay.Resident')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.IntegerField(default=0),
        ),
    ]
